### ISSUE TITLE
'ValueError: too many values to unpack (expected 3)' on sass-like arithmetic syntax

### ISSUE THREAD

**Issue by mgorny** [lesscpy/lesscpy#111]
I was trying to switch from sass to less, and I've missed one:

```
max-width: @page-width - 1ch;
```

lesscpy crashed on that:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/lesscpy", line 11, in <module>
    load_entry_point('lesscpy==0.14.0', 'console_scripts', 'lesscpy')()
  File "/usr/lib/python3.8/site-packages/lesscpy/scripts/compiler.py", line 236, in run
    p.parse(filename=args.target, debuglevel=args.debug)
  File "/usr/lib/python3.8/site-packages/lesscpy/lessc/parser.py", line 154, in parse
    self.post_parse()
  File "/usr/lib/python3.8/site-packages/lesscpy/lessc/parser.py", line 166, in post_parse
    out.append(pu.parse(self.scope))
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/block.py", line 42, in parse
    inner = list(utility.flatten([p.parse(scope) for p in inner if p]))
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/block.py", line 42, in <listcomp>
    inner = list(utility.flatten([p.parse(scope) for p in inner if p]))
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/block.py", line 42, in parse
    inner = list(utility.flatten([p.parse(scope) for p in inner if p]))
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/block.py", line 42, in <listcomp>
    inner = list(utility.flatten([p.parse(scope) for p in inner if p]))
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/property.py", line 38, in parse
    self.parsed = self.process(style, scope)
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/node.py", line 45, in process
    tokens = [
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/node.py", line 46, in <listcomp>
    t.parse(scope) if hasattr(t, 'parse') else t
  File "/usr/lib/python3.8/site-packages/lesscpy/plib/expression.py", line 35, in parse
    A, O, B = [
ValueError: too many values to unpack (expected 3)
```

**Comment by mgorny** [comment]
Hmm, that actually seems valid LESS and `lessc` seems to handle it just fine.
