### ISSUE TITLE
negated sub-expression fails with ValueError: too many values to unpack

### ISSUE THREAD

**Issue by danc86** [lesscpy/lesscpy#67]
A rule containing a negated arithmetic expression, such as -(1+1), fails.

Minimal reproducer input:

```
.c { left: -(1 + 1) * 1; }
```

Traceback (from current master, 8088fe58):

```
Traceback (most recent call last):
  File "scripts/lesscpy", line 16, in <module>
    compiler.run()
  File "lesscpy/scripts/compiler.py", line 178, in run
    p.parse(filename=args.target, debuglevel=args.debug)
  File "lesscpy/lessc/parser.py", line 156, in parse
    self.post_parse()
  File "lesscpy/lessc/parser.py", line 168, in post_parse
    out.append(pu.parse(self.scope))
  File "lesscpy/plib/block.py", line 43, in parse
    inner = list(utility.flatten([p.parse(scope) for p in inner if p]))
  File "lesscpy/plib/property.py", line 39, in parse
    self.parsed = self.process(style, scope)
  File "lesscpy/plib/node.py", line 49, in process
    for t in tokens]
  File "lesscpy/plib/expression.py", line 42, in parse
    if str(e).strip()]
ValueError: too many values to unpack
```

**Comment by danc86** [comment]
Looking at Expression#parse in pdb I was able to see that self.tokens for the outer expression is:

```
[['-', <lesscpy.plib.expression.Expression object at 0x7fc195004ad0>], '*', ('1',)]
```

where the inner expression is (1+1). After calling self.process on them, we get:

```
['-', '2', '*', '1']
```

which self.neg leaves untouched (it doesn't actually do the negation). It seems like the method is expecting some more like this, which is what happens when the input is `-2*1` instead of `-(1+1)*1`:

```
['-2', ' ', '*', '1']
```

**Comment by danc86** [comment]
Hmm actually I think that Expression#neg is *never* doing anything. I put an `assert False` inside its `if` block and the whole test suite passes without it firing.

Expression#neg seems to be trying to handle a case like `[['-', <Expression>], '*', '1']` which would be what you get here in this case, except that the flattening done by Node#process turns it into `['-', <Expression>, '*', '1']` before Expression#neg ever sees it.
